font_family Consolas Nerd Font
bold_font Consolas Nerd Font Bold
italic_font Consolas Nerd Font Italic
bold_italic_font Consolas Nerd Font Bold Italic
font_size 12

confirm_os_window_close 0
enable_audio_bell no
url_style straight
url_color white
window_padding_width 10
remember_window_size no
cursor_blink_interval 0.3
cursor_trail 1
background_opacity 0.8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
sync_to_monitor yes
selection_background #535353
selection_foreground #ffffff
mouse_hide_wait 0
cursor_shape beam
cursor_shape_unfocused beam
cursor_beam_thickness 1.0
map ctrl+backspace send_text all \x17
map ctrl+delete send_text all \x1bd
map ctrl+left send_text all \x1bb
map ctrl+right send_text all \x1bf
map home send_text all \x01
map end send_text all \x05
map ctrl+z send_text all \x1f
mouse_map right press ungrabbed paste_from_clipboard
map ctrl+equal  change_font_size all +2.0
map ctrl+minus  change_font_size all -2.0
map ctrl+0      change_font_size all 0
touch_scroll_multiplier 10.0

# material theme
foreground #eeffff
color1 #f07178
color2 #c3e88d
color3 #ffcb6b
color4 #82aaff
color5 #c792ea
color6 #89ddff
color9 #f07178
color10 #c3e88d
color11 #ffcb6b
color12 #82aaff
color13 #c792ea
color14 #89ddff