# built in laptop monitor
wallpaper {
    monitor = eDP-1
    path = ~/wallpapers/clouds/23260.jpg
    fit_mode = cover
}

# DELL monitor connected through HDMI
wallpaper {
    monitor = HDMI-A-1
    path = ~/wallpapers/cumulus.jpg
    fit_mode = cover
}

splash = false