local h = require("helpers")

h.qs_bind("SUPER + mouse:274", hl.dsp.window.close())
h.qs_bind("SUPER + SHIFT + right", hl.dsp.window.swap({ direction = "right" }))
h.qs_bind("SUPER + SHIFT + left", hl.dsp.window.swap({ direction = "left" }))
h.qs_bind("SUPER + SHIFT + up", hl.dsp.window.swap({ direction = "up" }))
h.qs_bind("SUPER + SHIFT + down", hl.dsp.window.swap({ direction = "down" }))
h.qs_bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }))
h.qs_bind("SUPER + slash", hl.dsp.layout("togglesplit"))
h.qs_bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
h.qs_bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
h.qs_bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
h.qs_bind("SUPER + down", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("SUPER + SHIFT + mouse:272", hl.dsp.window.resize(), { mouse = true })
h.qs_bind("SUPER + M", hl.dsp.window.move({ monitor = "+1", follow = true }))
h.qs_bind("F11", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
h.qs_bind("SUPER + F11", hl.dsp.window.fullscreen_state({ internal = 3, client = 3, action = "toggle" }))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("~/dotfiles/scripts/screenshot.sh region"))
hl.bind("Print", hl.dsp.exec_cmd("~/dotfiles/scripts/screenshot.sh"))

h.qs_bind("SUPER + W", function()
    local w = hl.get_active_window()
    if not w then return end
    if w.title == "qalc" then
        hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "C", state = "down" }))
        hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "C", state = "up" }))
    end
    hl.dispatch(hl.dsp.window.close())
end)

hl.bind("SUPER + SHIFT + I", function()
    hl.notification.create({ text = hl.get_active_window().title, timeout = 5000 })
end)

h.qs_bind("SUPER + mouse_up", function()
    hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "minus", state = "down" }))
    hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "minus", state = "up" }))
end)

h.qs_bind("SUPER + mouse_down", function()
    hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "equal", state = "down" }))
    hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "equal", state = "up" }))
end)
